--==========================================================================================================================
-- CIVILIZATIONS
--==========================================================================================================================
-- Types
-------------------------------------
INSERT INTO Types
		(Type,							Kind)
VALUES	('CIVILIZATION_LEU_HAITI',		'KIND_CIVILIZATION');

-------------------------------------
-- Civilizations
-------------------------------------
INSERT INTO Civilizations
		(CivilizationType,				Name,								Description,								Adjective,									StartingCivilizationLevelType,	RandomCityNameDepth,	Ethnicity)
VALUES	('CIVILIZATION_LEU_HAITI',		'LOC_CIVILIZATION_LEU_HAITI_NAME',	'LOC_CIVILIZATION_LEU_HAITI_DESCRIPTION',	'LOC_CIVILIZATION_LEU_HAITI_ADJECTIVE',	'CIVILIZATION_LEVEL_FULL_CIV',		10,						'ETHNICITY_AFRICAN');

-------------------------------------
-- CityNames
-------------------------------------
INSERT INTO CityNames
			(CivilizationType,					CityName)
VALUES		('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_01'), --Port-au-Prince (Default Capital)
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_02'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_03'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_04'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_05'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_06'), --Cap-Haitien (Capital for Fatiman, and potentially Henri Cristophe)
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_07'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_08'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_09'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_10'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_11'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_12'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_13'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_14'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_15'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_16'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_17'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_18'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_19'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_20'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_21'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_22'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_23'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_24'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_25'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_26'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_27'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_28'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_29'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_30'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_31'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_32'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_33'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_34'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_35'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_36'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_37'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_38'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_39'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_40'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_41'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_42'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_43'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_44'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_45'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_46'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_47'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_48'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_49'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_50'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_51'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_52'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_53'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_54'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_55'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_56'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_57'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_58'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_59'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_60'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_61'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_62'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_63'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_64'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_65'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_66'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_67'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_68'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_69'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_70'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_71'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_72'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_73'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_74'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_75'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_76'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_77'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_78'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_79'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_80'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_81'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_82'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_83'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_84'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_85'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_86'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_87'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_88'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_89'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_90'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_91'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_92'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_93'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_94'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_95'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_96'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_97'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_98'),
			('CIVILIZATION_LEU_HAITI',			'LOC_CITY_NAME_LEU_HAITI_99');

-------------------------------------
-- CivilizationCitizenNames
-------------------------------------
INSERT INTO CivilizationCitizenNames
		(CivilizationType,				CitizenName,								Female,		Modern)
VALUES	('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_1',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_2',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_3',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_4',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_5',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_6',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_7',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_8',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_9',				0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MALE_10',			0,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_1',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_2',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_3',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_4',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_5',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_6',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_7',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_8',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_9',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_FEMALE_10',			1,			0),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_1',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_2',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_3',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_4',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_5',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_6',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_7',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_8',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_9',		0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_MALE_10',	0,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_1',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_2',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_3',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_4',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_5',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_6',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_7',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_8',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_9',	1,			1),
		('CIVILIZATION_LEU_HAITI',		'LOC_CITIZEN_LEU_HAITI_MODERN_FEMALE_10',	1,			1);

-------------------------------------
-- StartBiasTerrains
-------------------------------------
INSERT INTO StartBiasTerrains
		(CivilizationType,				TerrainType,				Tier)
VALUES	('CIVILIZATION_LEU_HAITI',		'TERRAIN_COAST',			1),
		('CIVILIZATION_LEU_HAITI',		'TERRAIN_GRASS_HILLS',		3);


-------------------------------------
-- StartBiasFeatures
-------------------------------------
INSERT INTO StartBiasFeatures
		(CivilizationType,				FeatureType,			Tier)
VALUES	('CIVILIZATION_LEU_HAITI',		'FEATURE_REEF',			3);

-------------------------------------
-- StartBiasResources
-------------------------------------
--INSERT INTO StartBiasResources
--		(CivilizationType,				ResourceType,				Tier)
--VALUES	('CIVILIZATION_LEU_HAITI',		'RESOURCE_COCOA',			3);


-------------------------------------
-- StartBiasRivers
-------------------------------------
--INSERT INTO StartBiasRivers
--		(CivilizationType,				Tier)
--VALUES	('CIVILIZATION_LEU_HAITI',		3);


-------------------------------------
-- CivilizationInfo
-------------------------------------
INSERT INTO CivilizationInfo
		(CivilizationType,				Header,						Caption,								SortIndex)
VALUES	('CIVILIZATION_LEU_HAITI',		'LOC_CIVINFO_LOCATION',		'LOC_CIVINFO_LEU_HAITI_LOCATION',		10),
		('CIVILIZATION_LEU_HAITI',		'LOC_CIVINFO_SIZE',			'LOC_CIVINFO_LEU_HAITI_SIZE',			20),
		('CIVILIZATION_LEU_HAITI',		'LOC_CIVINFO_POPULATION',	'LOC_CIVINFO_LEU_HAITI_POPULATION',	30),
		('CIVILIZATION_LEU_HAITI',		'LOC_CIVINFO_CAPITAL', 		'LOC_CIVINFO_LEU_HAITI_CAPITAL',		40);


--==========================================================================================================================
-- GEDEMON YNAEMP
--==========================================================================================================================
-- StartPosition
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS StartPosition (MapName TEXT, Civilization TEXT, Leader TEXT, X INT default 0, Y INT default 0);
INSERT OR REPLACE INTO StartPosition
		(Civilization,					MapName,					X,		Y)
VALUES	('CIVILIZATION_LEU_HAITI',		'GiantEarth',				154,	47),
		('CIVILIZATION_LEU_HAITI',		'GreatestEarthMap',			26,		35),
		('CIVILIZATION_LEU_HAITI',		'LargestEarth',				205,	60),
		('CIVILIZATION_LEU_HAITI',		'Zobtzler_TheAmericas_Map',	52,		33);


--==========================================================================================================================
-- JFD RULE WITH FAITH
--==========================================================================================================================
-- Civilization_Titles
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS
	Civilization_Titles (
	CivilizationType  				text 		 		default null,
	GovernmentType					text 	 			default null,
	LeaderTitle						text				default null,
	PolicyType  					text 		 		default null);

CREATE TRIGGER Haiti_JFDRwF_Check
AFTER INSERT ON Governments
WHEN NEW.GovernmentType = 'GOVERNMENT_JFD_NOBLE_REPUBLIC'
BEGIN
INSERT INTO Civilization_Titles
		(CivilizationType, 			GovernmentType, 							PolicyType,				LeaderTitle)
VALUES	('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_CHIEFDOM',						null,					'LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_JFD_HORDE',						null,					'LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_JFD_POLIS',						null,					'LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_AUTOCRACY',						null,					'LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_OLIGARCHY',						null,					'LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_CLASSICAL_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_MERCHANT_REPUBLIC',				null,					'LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_MONARCHY',						null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_JFD_ABSOLUTE_MONARCHY',			null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_JFD_CONSTITUTIONAL_MONARCHY',	null,					'LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_JFD_NOBLE_REPUBLIC',			null,					'LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_DEMOCRACY',						null,					'LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_COMMUNISM',						null,					'LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_LEU_HAITI'),
		('CIVILIZATION_LEU_HAITI',	'GOVERNMENT_FASCISM',						null,					'LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_LEU_HAITI');
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_LEU_HAITI' AND GovernmentType IS NOT null AND GovernmentType NOT IN (SELECT GovernmentType FROM Governments);
DELETE FROM Civilization_Titles WHERE CivilizationType = 'CIVILIZATION_LEU_HAITI' AND PolicyType IS NOT null AND PolicyType NOT IN (SELECT PolicyType FROM Policies);

END;
---
------------------------------------------------------------
--CivilizationPoliticianNames
------------------------------------------------------------
--FirstMinisterType can be null. Otherwise, types are:
-- JFD_FIRST_MINISTER_LAWGIVER
-- JFD_FIRST_MINISTER_ORACLE
-- JFD_FIRST_MINISTER_SOLDIER
-- JFD_FIRST_MINISTER_BURGHER
-- JFD_FIRST_MINISTER_CLERIC
-- JFD_FIRST_MINISTER_NOBLE
-- JFD_FIRST_MINISTER_CONSERVATIVE
-- JFD_FIRST_MINISTER_LIBERAL
-- JFD_FIRST_MINISTER_MODERATE
-- JFD_FIRST_MINISTER_NATIONALIST
-- JFD_FIRST_MINISTER_NEO_LIBERAL
-- JFD_FIRST_MINISTER_SOCIALIST
CREATE TABLE IF NOT EXISTS
	CivilizationPoliticianNames (
	CivilizationType  										text 		 																			default null,
	PoliticianName											text 		 																			default null,
	FirstMinisterType										text 		 																			default null,
	Female													boolean																					default 0,
	Modern  												boolean																					default 0,
	IsNoSpace												boolean																					default 0,
PRIMARY KEY(CivilizationType, PoliticianName),
FOREIGN KEY(CivilizationType) REFERENCES Civilizations(CivilizationType) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO CivilizationPoliticianNames
		(CivilizationType, 			PoliticianName,						Female)
VALUES	('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_01',		1),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_02',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_03',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_04',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_05',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_06',		1),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_07',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_08',		1),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_09',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_10',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_11',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_12',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_13',		1),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_14',		0),
		('CIVILIZATION_LEU_HAITI',	'LOC_POLITICIAN_LEU_HAITI_15',		0);


--==========================================================================================================================
--==========================================================================================================================
